### ISSUE TITLE
装不了IPK(Glinet X3000, aarch64_cortex-a53)

### ISSUE THREAD

**Issue by qy2009** [QiuSimons/luci-app-daed#17]
我用了那个aarch64_generic的。。。不行。。。我是用的gl-inet路由器的原版firmware...

![image](https://github.com/QiuSimons/luci-app-daed/assets/51539377/bf7d6a2e-fa5d-4bcc-bf32-b7f903da0748)

**Comment by QiuSimons** [comment]
两个问题
首先你daed核心都不装，直接装luci，肯定会报错啊，你倒是看他的提示啊！
第二个问题，你没读readme，你一个原版固件，10000%是不会开启bpf的，就算你装上了，daed也是无法工作的
