### ISSUE TITLE
 * pkg_hash_check_unresolved: cannot find dependency libcron for luci-app-daed

### ISSUE THREAD

**Issue by essoojay** [QiuSimons/luci-app-daed#19]
How to solve error as above, am trying to compile daed on snapshot openwrt and i keep runnig into the error as above

e.g

 * pkg_hash_check_unresolved: cannot find dependency libcron for luci-app-daed

thanks

**Comment by Small-Ku** [comment]
You may found it at https://github.com/immortalwrt/packages/tree/master/libs/libcron or https://github.com/kenzok8/small-package/tree/main/libcron
