### ISSUE TITLE
dae官方好像升级到8.0版本了，申请跟进

### ISSUE THREAD

**Issue by yt1988** [QiuSimons/luci-app-daed#26]
如题，再次感谢大佬开发，对于代码能力差我的我来说，基于GUI进行配置很好用。

**Comment by QiuSimons** [comment]
但凡你看一眼这里的版本号也不至于提这样的issue

**Comment by yt1988** [comment]
抱歉，可能是我openwrt源的问题，我从github重新下载下。

再次感谢辛勤开发

**Comment by yt1988** [comment]
> 但凡你看一眼这里的版本号也不至于提这样的issue

检查了下，我是从openwrt后台的软件源去下载的，下载的也确实是“luci-app-daed”，包名完全相同。

最新版本为：git-25.280.04805-6f563c1，对应关联dae版本为0.6.0-3

极致困惑，不知道是哪里出了问题

![image](https://github.com/user-attachments/assets/52e5f7bb-77ff-4e1e-b794-b8907587857c)

**Comment by QiuSimons** [comment]
你是用的并不是本项目
