### ISSUE TITLE
我在menuconfig上找不到啊

### ISSUE THREAD

**Issue by ZhuangJW** [QiuSimons/luci-app-daed#27]
按照README,我进入了immortalwrt目录下，然后运行了git clone https://github.com/QiuSimons/luci-app-daed package/dae，之后make update -a 和make install -a，再之后我在make menuconfig上找不到呢

**Comment by davidtall** [comment]
```
#  基本 XDP 支持
echo "CONFIG_XDP=y" >> ./.config
# XDP Sockets
echo "CONFIG_XDP_SOCKETS=y" >> ./.config
```

**Comment by QiuSimons** [comment]
都menuconfig了，用“/”键来搜索，然后看depends，然后根据这个调整自己的config来meet编译需要我觉得不是很难的事情。

**Comment by davidtall** [comment]
> 都menuconfig了，用“/”键来搜索，然后看depends，然后根据这个调整自己的config来meet编译需要我觉得不是很难的事情。 有时候开启某个你需要的depends，需要开启这个depends的depends，这不是一个应该由开发者教的事情。
> 
> 再抱怨两句
> 
> https://github.com/QiuSimons/luci-app-daed/blob/844a5c3aba523763f87049340cab18f7d6acc8d6/README.md?plain=1#L41
> 
> 
> 这里写入要引入新模块，而且仔细阅读会发现，这个引入的模块实际上会开启CONFIG_KERNEL_XDP_SOCKETS=y

大佬可能是因为 immortalwrt 的源码 package/kernel/linux/modules/netsupport.mk 已经包含了xdp-sockets-diag
，但少了一句CONFIG_XDP_SOCKETS=y ，又不想改源码，所以在.config 中加一句CONFIG_KERNEL_XDP_SOCKETS=y是最省事的。

https://github.com/immortalwrt/immortalwrt/blob/8cd8319216ffb182c35582e43962e98ecf9e9ccd/package/kernel/linux/modules/netsupport.mk#L1497

**Comment by QiuSimons** [comment]
> > 都menuconfig了，用“/”键来搜索，然后看depends，然后根据这个调整自己的config来meet编译需要我觉得不是很难的事情。 有时候开启某个你需要的depends，需要开启这个depends的depends，这不是一个应该由开发者教的事情。
> > 再抱怨两句
> > https://github.com/QiuSimons/luci-app-daed/blob/844a5c3aba523763f87049340cab18f7d6acc8d6/README.md?plain=1#L41
> > 
> > 这里写入要引入新模块，而且仔细阅读会发现，这个引入的模块实际上会开启CONFIG_KERNEL_XDP_SOCKETS=y
> 
> 大佬可能是因为 immortalwrt 的源码 package/kernel/linux/modules/netsupport.mk 已经包含了xdp-sockets-diag ，但少了一句CONFIG_XDP_SOCKETS=y ，又不想改源码，所以在.config 中加一句CONFIG_KERNEL_XDP_SOCKETS=y是最省事的。
> 
> > https://github.com/immortalwrt/immortalwrt/blob/8cd8319216ffb182c35582e43962e98ecf9e9ccd/package/kernel/linux/modules/netsupport.mk#L1497-L1504

就算要加也应该是CONFIG_PACKAGE_kmod-xdp-sockets-diag=y
